//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.22 at 11:15:26 AM CEST 
//


package CarbonCare;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactoryResponse {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactoryResponse() {
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi }
     * 
     */
    public CarbonCareResponseApi createCarbonCareResponseApi() {
        return new CarbonCareResponseApi();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response }
     * 
     */
    public CarbonCareResponseApi.Response createCarbonCareResponseApiResponse() {
        return new CarbonCareResponseApi.Response();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments createCarbonCareResponseApiResponseShipments() {
        return new CarbonCareResponseApi.Response.Shipments();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments.Shipment }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments.Shipment createCarbonCareResponseApiResponseShipmentsShipment() {
        return new CarbonCareResponseApi.Response.Shipments.Shipment();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions createCarbonCareResponseApiResponseShipmentsShipmentEmmissions() {
        return new CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments.Shipment.CompensationCosts }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments.Shipment.CompensationCosts createCarbonCareResponseApiResponseShipmentsShipmentCompensationCosts() {
        return new CarbonCareResponseApi.Response.Shipments.Shipment.CompensationCosts();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments.Shipment.Distance }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments.Shipment.Distance createCarbonCareResponseApiResponseShipmentsShipmentDistance() {
        return new CarbonCareResponseApi.Response.Shipments.Shipment.Distance();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments.Shipment.Status }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments.Shipment.Status createCarbonCareResponseApiResponseShipmentsShipmentStatus() {
        return new CarbonCareResponseApi.Response.Shipments.Shipment.Status();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.OPS }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.OPS createCarbonCareResponseApiResponseShipmentsShipmentEmmissionsOPS() {
        return new CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.OPS();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.TOT }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.TOT createCarbonCareResponseApiResponseShipmentsShipmentEmmissionsTOT() {
        return new CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.TOT();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.ENE }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.ENE createCarbonCareResponseApiResponseShipmentsShipmentEmmissionsENE() {
        return new CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.ENE();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.TKM }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.TKM createCarbonCareResponseApiResponseShipmentsShipmentEmmissionsTKM() {
        return new CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.TKM();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.TOTEI }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.TOTEI createCarbonCareResponseApiResponseShipmentsShipmentEmmissionsTOTEI() {
        return new CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.TOTEI();
    }

    /**
     * Create an instance of {@link CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.Compensation }
     * 
     */
    public CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.Compensation createCarbonCareResponseApiResponseShipmentsShipmentEmmissionsCompensation() {
        return new CarbonCareResponseApi.Response.Shipments.Shipment.Emmissions.Compensation();
    }

}
