//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 08:42:20 AM CEST 
//


package CarbonCare;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactoryRequest {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactoryRequest() {
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi }
     * 
     */
    public CarbonCareRequestApi createCarbonCareRequestApi() {
        return new CarbonCareRequestApi();
    }

    /**
     * Create an instance of {@link SeaAddressType }
     * 
     */
    public SeaAddressType createSeaAddressType() {
        return new SeaAddressType();
    }

    /**
     * Create an instance of {@link AirAddressType }
     * 
     */
    public AirAddressType createAirAddressType() {
        return new AirAddressType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi.Request }
     * 
     */
    public CarbonCareRequestApi.Request createCarbonCareRequestApiRequest() {
        return new CarbonCareRequestApi.Request();
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi.Request.Shipments }
     * 
     */
    public CarbonCareRequestApi.Request.Shipments createCarbonCareRequestApiRequestShipments() {
        return new CarbonCareRequestApi.Request.Shipments();
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi.Request.Shipments.Shipment }
     * 
     */
    public CarbonCareRequestApi.Request.Shipments.Shipment createCarbonCareRequestApiRequestShipmentsShipment() {
        return new CarbonCareRequestApi.Request.Shipments.Shipment();
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi.Request.Shipments.Shipment.Legs }
     * 
     */
    public CarbonCareRequestApi.Request.Shipments.Shipment.Legs createCarbonCareRequestApiRequestShipmentsShipmentLegs() {
        return new CarbonCareRequestApi.Request.Shipments.Shipment.Legs();
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg }
     * 
     */
    public CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg createCarbonCareRequestApiRequestShipmentsShipmentLegsLeg() {
        return new CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link SeaAddressType.Coordinates }
     * 
     */
    public SeaAddressType.Coordinates createSeaAddressTypeCoordinates() {
        return new SeaAddressType.Coordinates();
    }

    /**
     * Create an instance of {@link AirAddressType.Coordinates }
     * 
     */
    public AirAddressType.Coordinates createAirAddressTypeCoordinates() {
        return new AirAddressType.Coordinates();
    }

    /**
     * Create an instance of {@link AddressType.Coordinates }
     * 
     */
    public AddressType.Coordinates createAddressTypeCoordinates() {
        return new AddressType.Coordinates();
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Air }
     * 
     */
    public CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Air createCarbonCareRequestApiRequestShipmentsShipmentLegsLegAir() {
        return new CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Air();
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Sea }
     * 
     */
    public CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Sea createCarbonCareRequestApiRequestShipmentsShipmentLegsLegSea() {
        return new CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Sea();
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Rail }
     * 
     */
    public CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Rail createCarbonCareRequestApiRequestShipmentsShipmentLegsLegRail() {
        return new CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Rail();
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Truck }
     * 
     */
    public CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Truck createCarbonCareRequestApiRequestShipmentsShipmentLegsLegTruck() {
        return new CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Truck();
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Iww }
     * 
     */
    public CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Iww createCarbonCareRequestApiRequestShipmentsShipmentLegsLegIww() {
        return new CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Iww();
    }

    /**
     * Create an instance of {@link CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Ferry }
     * 
     */
    public CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Ferry createCarbonCareRequestApiRequestShipmentsShipmentLegsLegFerry() {
        return new CarbonCareRequestApi.Request.Shipments.Shipment.Legs.Leg.Ferry();
    }

}
