/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.riege.onerecord.carbonator;

import org.junit.jupiter.api.Test;

import com.riege.onerecord.carbulator.CarbulatorEngine;

import static org.junit.jupiter.api.Assertions.*;

class CarbulatorEngineTest {

    @Test void appHasAGreeting() {
        CarbulatorEngine classUnderTest = new CarbulatorEngine();
        assertNotNull(classUnderTest.toString(), "app should have a greeting");
    }
}
